//! Schema migration set for `main.db`, wired to the shared migration runner.
//!
//! The set of migrations is discovered at build time by `build.rs`, which scans
//! `sql/*.sql`, verifies the files form a gapless `0..N` sequence, and embeds them
//! into the binary as [`EMBEDDED_MIGRATIONS`]. Nothing about the migration list is
//! hand-maintained in source — adding a migration means dropping a new numbered
//! `.sql` file into `sql/`.
//!
//! The generic runner that applies and integrity-checks a migration set —
//! [`run`], [`EmbeddedMigration`], `user_version`, and the tracking/adoption logic
//! — lives in the shared `kls-web-core` crate (see DASHBOARD_DECOUPLING_PLAN.md,
//! Phase 3) and is re-exported here so existing `crate::migrations::…` call sites
//! (including the request-log migration set in `logging.rs`) are unchanged. Only
//! the build-time-embedded set and the `main.db` entry points stay app-side.

pub use kls_web_core::migrations::*;

// Pulls in `pub const EMBEDDED_MIGRATIONS: [EmbeddedMigration; N]` generated by
// build.rs. Kept as an `include!` so the array literal is type-checked against the
// `EmbeddedMigration` struct re-exported above.
include!(concat!(env!("OUT_DIR"), "/migrations_generated.rs"));

/// Name of the table tracking applied migrations and their checksums.
const TRACKING_TABLE: &str = "schema_migrations";

/// The version `main.db` reaches once every embedded migration is applied, equal to
/// the migration count.
pub fn target_version() -> u32 {
    EMBEDDED_MIGRATIONS.len() as u32
}

/// Runs all pending `main.db` migrations and verifies the integrity of applied ones.
///
/// This is the function handed to the connection pool's `with_init`. It assumes the
/// pool has already configured connection-level pragmas (`busy_timeout`,
/// `journal_mode=WAL`, …) so concurrent invocations can serialise on the write lock
/// rather than failing with `SQLITE_BUSY`.
pub fn migrate(conn: &mut rusqlite::Connection) -> anyhow::Result<()> {
    run(conn, &EMBEDDED_MIGRATIONS, TRACKING_TABLE)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn open_memory() -> rusqlite::Connection {
        let conn = rusqlite::Connection::open_in_memory().expect("open in-memory db");
        conn.busy_timeout(std::time::Duration::from_secs(5)).unwrap();
        conn
    }

    #[test]
    fn embedded_migrations_are_contiguous() {
        for (index, migration) in EMBEDDED_MIGRATIONS.iter().enumerate() {
            assert_eq!(
                migration.version as usize, index,
                "migration {index} is out of sequence"
            );
        }
        assert!(
            !EMBEDDED_MIGRATIONS.is_empty(),
            "expected at least one embedded migration"
        );
    }

    #[test]
    fn migrate_fresh_database_reaches_target() {
        let mut conn = open_memory();
        migrate(&mut conn).expect("migrate fresh db");
        assert_eq!(user_version(&conn).unwrap(), target_version());

        let count: u32 = conn
            .query_row(&format!("SELECT COUNT(*) FROM {TRACKING_TABLE}"), [], |r| r.get(0))
            .unwrap();
        assert_eq!(count, target_version());
    }

    #[test]
    fn migrate_is_idempotent() {
        let mut conn = open_memory();
        migrate(&mut conn).expect("first migrate");
        migrate(&mut conn).expect("second migrate");
        assert_eq!(user_version(&conn).unwrap(), target_version());
    }

    fn table_exists(conn: &rusqlite::Connection, table: &str) -> bool {
        conn.query_row(
            "SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name = ?",
            [table],
            |row| row.get::<_, i64>(0),
        )
        .unwrap()
            > 0
    }

    #[test]
    fn all_expected_tables_exist_after_fresh_migration() {
        let mut conn = open_memory();
        conn.execute_batch("PRAGMA foreign_keys = ON;").unwrap();
        migrate(&mut conn).expect("migrate fresh db");

        for table in [
            "account",
            "session",
            "storage",
            "audit_log",
            "images",
            "short_link",
            "paste",
            "paste_revision",
            "totp_recovery_code",
            "user_discord_links",
            "guild_api_key",
            "username_change",
        ] {
            assert!(table_exists(&conn, table), "{table} must exist");
        }
    }

    fn table_has_column(conn: &rusqlite::Connection, table: &str, column: &str) -> bool {
        conn.prepare(&format!("PRAGMA table_info({table})"))
            .unwrap()
            .query_map([], |row| row.get::<_, String>(1))
            .unwrap()
            .filter_map(Result::ok)
            .any(|name| name == column)
    }

    #[test]
    fn schema_columns_match_model_expectations() {
        let mut conn = open_memory();
        migrate(&mut conn).expect("migrate fresh db");

        assert!(table_has_column(&conn, "session", "scopes"));
        assert!(table_has_column(&conn, "images", "expires_at"));
        assert!(table_has_column(&conn, "images", "guild_id"));
        assert!(table_has_column(&conn, "user_discord_links", "discord_avatar"));
        assert!(table_has_column(&conn, "paste", "enc_salt"));
        assert!(table_has_column(&conn, "paste", "burn_after_read"));
        assert!(table_has_column(&conn, "paste", "fork_of"));
    }
}
